// openmed-nuxt3/layouts/layout.vue
<script setup>
const isDrawerOpen = ref(false);
</script>

<template>
  <div>
    <!-- Mobile Menu, open iff we clicked on the drawer button -->
    <LayoutMobileMenu :isOpen="isDrawerOpen" />

    <div class="grid grid-flow-col md:grid-cols-[auto_1fr]">
      <LayoutDesktopMenu />

      <div class="relative min-h-screen flex flex-col">
        <header
          class="sm:hidden p-6 flex flex-row justify-between md:justify-end items-center"
        >
          <!-- Drawer Button + Small Logo -->
          <div>
            <!-- OpenMed's small logo -->
            <NuxtLink to="/">
              <img
                src="/img/logo-openmed/openmed-logo.svg"
                alt="Il logo di openmed."
              />
            </NuxtLink>
          </div>

          <!-- Drawer Button -->
          <div
            class="flex sm:hidden rounded-lg hover:bg-brandBlue-50/20 justify-center items-center"
          >
            <button
              class="p-4 material-icons-round focus:outline-none text-brandGreen-500"
              @click.prevent="isDrawerOpen = !isDrawerOpen"
            >
              menu
            </button>
          </div>
        </header>

        <main
          class="transition-all md:blur-none"
          :class="isDrawerOpen ? 'blur-sm' : 'blur-none'"
        >
          <slot />
        </main>

        <footer />
      </div>
    </div>

    <!-- TODO: add static footer -->
  </div>
</template>

// openmed-svelte/src/routes/__layout.svelte
<script context="module">
  export async function load({ session }) {
    // If the user is logged in already, let this component know
    return {
      // props: {
      //   userId: session?.id
      // }
    };
  }
</script>

<script>
  import { goto } from '$app/navigation';
  import { session } from '$app/stores';
  import { usersEndpoint } from '$lib/uri';
  import { fade } from 'svelte/transition';
  import '../app.css';

  // export let userId;
  let isDrawerOpen = false;

  // async function logout() {
  //   await fetch(`${usersEndpoint}/signout`, {
  //     method: 'POST',
  //     credentials: 'include'
  //   });
  //   $session = null;
  //   goto('/login');
  // }
</script>

<!-- reimplement the logout button later on -->
<!-- {#if userId}
  <p on:click|preventDefault={() => logout()}>Done? Logout here</p>
{/if} -->

<div
  class="{isDrawerOpen
    ? 'fixed'
    : 'hidden'} z-10 top-20 md:hidden fixed w-full h-full bg-brandBlack-50 opacity-40"
  on:click={() => (isDrawerOpen = false)}
/>

<!-- Mobile Nav Bar -->
{#if isDrawerOpen}
  <div
    transition:fade
    class="fixed transition-all top-20 z-40 p-4 pb-20 md:hidden bg-white w-full right-0"
  >
    <nav>
      <!-- TODO: use a loop -->
      <ul class="flex flex-col items-end list-none">
        <a href="/"><li class="font-light py-2">Home</li></a>
        <a href="/"><li class="font-light py-2">Gestisci Utenti</li></a>
        <a href="/"><li class="font-light py-2">Crea Appuntamento</li></a>
        <a href="/"><li class="font-light py-2">Lista Appuntamenti</li></a>
        <a href="/"><li class="font-light py-2">Contatti</li></a>
      </ul>
    </nav>
  </div>
{/if}

<div class="relative min-h-screen flex flex-col">
  <!-- Header / Navigation Bar / Menu / Side Nav Bar -->
  <header class="p-6">
    <!-- Main Navigation Bar -->
    <div class="flex flex-row flex-nowrap justify-between items-center">
      <!-- Use OpenMed's logo here -->
      <div>
        <a href="/">
          <img src="/static/img/openmed-logo.svg" alt="Il logo di openmed." />
        </a>
      </div>

      <!-- Drawer Menu on mobile screens -->
      <div
        class="flex md:hidden w-10 h-10 rounded-lg hover:bg-brandBlue-50/20 justify-center items-center"
      >
        <button
          class="material-icons-round focus:outline-none text-5xl text-brandGreen-500"
          on:click|preventDefault={() => (isDrawerOpen = !isDrawerOpen)}
        >
          menu
        </button>
      </div>

      <!-- Navigation elements on wider screens -->
      <nav class="hidden md:block">
        <ul class="list-none flex flex-row justify-center items-center">
          <a href="/"><li class="font-light px-3">Home</li></a>
          <a href="/"><li class="font-light px-3">Gestisci Utenti</li></a>
          <a href="/"><li class="font-light px-3">Crea Appuntamento</li></a>
          <a href="/"><li class="font-light px-3">Lista Appuntamenti</li></a>
          <a href="/"><li class="font-light px-3">Contatti</li></a>
        </ul>
      </nav>
    </div>
  </header>

  <main class="{isDrawerOpen ? 'blur-sm' : 'blur-none'} flex-1 mx-4 my-4">
    <slot />
  </main>

  <footer />
</div>

<!-- TODO: add static footer -->
