// openmed-vue/src/pages/login/index.vue
<script setup>
import { validate } from "validate.js";

useHead({ title: `Login` });

const { login } = useAuth();
const { getUser } = useUser();

let hasStarted = ref(false);

// Initialize form values
const choices = ref({
  username: undefined,
  password: undefined,
});

// Initialize form constraints
const formConstraints = {
  username: {
    presence: {
      allowEmpty: false,
      message: `^Devi inserire un username`,
    },
  },
  password: {
    presence: {
      allowEmpty: false,
      message: `^Devi inserire la tua password`,
    },
  },
};
let errors = ref({});
let asyncErrors = ref(null);

// async function getUserData() {
//   const { data: response } = await useFetch(`${$usersEndpoint()}/currentuser`, {
//     mode: "cors",
//     credentials: "include",
//     headers: {
//       "Access-Control-Allow-Origin": "*",
//     },
//   });
//   // If something goes wrong with this call, we can't authenticate
//   if (!response.ok) return null;

//   // If we got a proper response body, we extract its currentUser prop
//   const responseBody = response;
//   const currentUser = responseBody.currentUser;
//   if (!currentUser) return null;

//   return { ...currentUser };
// }

async function loginWithCredentials() {
  errors.value = validate(choices.value, formConstraints);
  if (errors.value) return;

  try {
    // username: choices.value.username,
    //       password: choices.value.password,

    await login({
      username: choices.value.username,
      password: choices.value.password,
    });

    await getUser();

    asyncErrors.value = null;
    navigateTo("/");
  } catch (err) {
    console.log(err);
    asyncErrors.value = err?.statusText;
  }
}
</script>

<template>
  <div>
    <div
      class="bg-no-repeat bg-center bg-cover bg-[url('img/login-background.png')] h-screen flex flex-col px-8 py-16 items-center justify-between"
    >
      <img
        src="@/assets/img/logo-openmed/openmed-logo-full.svg"
        alt="Il logo di Openmed"
      />
      <div id="login" class="grid grid-rows-1 grid-cols-1">
        <StyledButton
          v-if="!hasStarted"
          @click="hasStarted = true"
          class="font-bold"
          spaces="px-16 py-2"
        >
          Inizia
        </StyledButton>
        <div v-else>
          <p class="my-4">Inserisci il tuo username e la tua password</p>
          <form
            @submit.prevent="loginWithCredentials"
            id="signin"
            class="flex flex-col justify-center items-center"
            novalidate
          >
            <fieldset>
              <input
                type="text"
                name="Username"
                placeholder="username"
                id="username"
                class="my-1 appearance-none px-2 py-1 rounded-3xl bg-brandBlue-50/25 hover:bg-brandBlue-50/40"
                v-model="choices.username"
                required
              />
            </fieldset>
            <div v-if="errors?.username" class="my-4 text-red-500">
              {{ errors.username[0] }}
            </div>
            <fieldset>
              <input
                label="Password"
                placeholder="password"
                id="psw"
                name="psw"
                type="password"
                class="my-1 appearance-none px-2 py-1 bg-brandBlue-50/25 hover:bg-brandBlue-50/40 shadow-sm rounded-3xl"
                v-model="choices.password"
              />
            </fieldset>
            <div v-if="errors?.password" class="my-4 text-red-500">
              {{ errors.password[0] }}
            </div>
            <button
              type="submit"
              class="submit inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
            >
              Accedi
            </button>
          </form>
          <div v-if="asyncErrors" class="my-4 text-center text-red-500">
            {{ asyncErrors }}
          </div>
        </div>
      </div>

      <img
        class="w-40"
        src="@/assets/img/logo-fais/logo-fais.png"
        alt="Il logo di FAIS"
      />
    </div>
  </div>
</template>

// openmed-svelte/src/routes/login/index.svelte
<script context="module">
  export async function load({ session }) {
    // If the user is logged in already, re-route him to the index
    if (session?.id) {
      return {
        status: 302,
        redirect: '/'
      };
    }

    return {};
  }
</script>

<script>
  import { validate } from 'validate.js';
  import { goto } from '$app/navigation';
  import { session } from '$app/stores';
  import { usersEndpoint } from '$lib/uri.js';

  let hasStarted = false;

  // Initialize form values
  const form = {
    username: undefined,
    password: undefined
  };

  // Initialize form constraints
  const formConstraints = {
    username: {
      presence: {
        allowEmpty: false,
        message: `^Devi inserire un username`
      }
      // We are NOT checking a proper email since this mode is deprecated
    },
    password: {
      presence: {
        allowEmpty: false,
        message: `^Devi inserire la tua password`
      }
    }
  };
  let errors;

  async function getUserData() {
    const response = await fetch(`${usersEndpoint}/currentuser`, { credentials: 'include' });
    // If something goes wrong with this call, we can't authenticate
    if (!response.ok) return null;

    // If we got a proper response body, we extract its currentUser prop
    const responseBody = await response.json();
    const currentUser = responseBody.currentUser;
    if (!currentUser) return null;

    return { ...currentUser };
  }

  async function logIn() {
    // Form validation
    errors = validate(form, formConstraints);
    if (errors) {
      console.log(errors);
      return;
    }

    // Log in request
    const response = await fetch(`${usersEndpoint}/signin`, {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        email: form.username,
        password: form.password
      })
    });

    if (response.ok) {
      $session = await getUserData();
      goto('/');
    } else {
      const errors = await response.json();
      // TODO properly handle errors
      console.log(errors);
    }
  }
</script>

<svelte:head>
  <title>Log-in - OpenMed</title>
</svelte:head>

{#if !hasStarted}
  <button on:click={() => (hasStarted = true)} class="start">Inizia</button>
{:else}
  <form on:submit|preventDefault={logIn} id="signin">
    <!-- TODO: valutare se aggiungere delle label per accessibilità -->
    <fieldset>
      <input
        bind:value={form.username}
        label="Username"
        placeholder="Username"
        id="ssn"
        name="ssn"
        type="text"
        class="sh adow-sm focus:ring-green-600 focus:border-green-500 block w-full sm:text-sm border-gray-300 rounded-md"
      />
    </fieldset>
    {#if errors?.username}
      <div class="error">{errors.username[0]}</div>
    {/if}
    <fieldset>
      <input
        bind:value={form.password}
        label="Password"
        placeholder="Password"
        id="psw"
        name="psw"
        type="password"
        class="shadow-sm focus:ring-green-600 focus:border-green-500 block w-full sm:text-sm border-gray-300 rounded-md"
      />
    </fieldset>
    {#if errors?.password}
      <div class="error">{errors.password[0]}</div>
    {/if}
    <button
      type="submit"
      class="submit inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
    >
      Accedi
    </button>
  </form>
{/if}

<!-- TODO: add proper static assets, here -->
<!-- <img src="fais-logo.svg" alt=""/>
<br/>
<img src="sponsor1.svg" alt=""/>
<img src="sponsor2.svg" alt=""/>
<img src="sponsor2.svg" alt=""/> -->
