// client/components/Users/FilterButton.vue
<script setup>
const emit = defineEmits(["click"]);

const isApplied = ref(false);
function apply() {
  isApplied.value = !isApplied.value;
  emit("click");
}

const appliedStyles = computed(() =>
  isApplied.value
    ? "font-bold text-brandBlue-500"
    : "font-normal text-brandBlue-50"
);
</script>

<template>
  <button
    @click="apply"
    class="my-2 px-4 py-1 rounded-full hover:text-brandBlue-500 hover:bg-brandBlue-50/50"
    :class="appliedStyles"
    @click.prevent.stop="emit('click')"
  >
    <slot />
  </button>
</template>

// openmed-svelte/src/lib/pages/users/FilterButton.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  let isApplied = false;
  function apply() {
    isApplied = !isApplied;
    dispatch('apply');
  }

  $: isBold = isApplied ? 'font-bold' : 'font-normal';
  $: color = isApplied ? 'text-brandBlue-500' : 'text-brandBlue-50';
</script>

<span
  on:click|preventDefault={apply}
  class="hover:bg-brandBlue-50/50 cursor-pointer rounded-full my-2 {color} hover:text-brandBlue-500 text-center {isBold} px-3 py-1"
>
  <slot />
</span>
