// openmed-vue/src/components/StyledButton.vue
<!-- this component should be trashed as it is now -->

<script setup>
const props = defineProps({
  class: String,
  colors: {
    type: String,
    default: "text-white bg-brandBlue-500 hover:bg-brandBlue-700",
  },
  spaces: { type: String, default: "px-4 py-2 my-1" },
});

const myClasses = props.class;
const emit = defineEmits(["click"]);
</script>

<template>
  <button
    class="rounded-3xl"
    :class="`${myClasses} ${colors} ${spaces}`"
    @click.prevent.stop="emit('click')"
  >
    <slot />
  </button>
</template>

// openmed-svelte/src/lib/shared/StyledButton.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export { additionalClasses as class };
  let additionalClasses = '';

  export let colors = 'text-white bg-brandBlue-500 hover:bg-brandBlue-700';
  export let spaces = 'px-4 py-2 my-1';

  const dispatch = createEventDispatcher();
</script>

<button
  class="rounded-3xl {additionalClasses} {colors} {spaces}"
  on:click|stopPropagation|preventDefault={() => dispatch('click')}
>
  <slot />
</button>
